### ISSUE TITLE
Getting Ambiguous class resolution, "MigrationCartalystSentryInstallUsers"  in Composer version 1.0-dev

### ISSUE THREAD

**Issue by ideadx** [rydurham/Sentinel#161] opened 2015-07-09 11:42 UTC

**Comment by rydurham** [comment] 2015-07-09 19:13
What is the context in which this is coming up?

**Comment by ideadx** [comment] 2015-07-13 11:41
@rydurham When running: 'composer update' or 'composer install' command 
http://imgur.com/kez1Kta
Thx.

**Comment by rydurham** [comment] 2015-07-13 15:57
Interesting.  I am not able to reproduce this on Laravel 5.  Would you send me a stack trace?

**Comment by ideadx** [comment] 2015-07-16 07:32
I have standard install of Mamp Pro on iMac. I think it has to do with psr-0 loader classmap entries.

**Comment by rydurham** [comment] 2015-07-16 09:44
I have a plan for fixing this, but I am not sure when I will be able to implement it.

**Comment by ideadx** [comment] 2015-07-16 23:20
@rydurham Thanks :+1:

**Comment by rydurham** [comment] 2015-07-20 18:28
This should now be fixed in v2.2.3.

**Comment by ideadx** [comment] 2015-07-25 06:37
Sorry mate but I just pulled in 2.2.3 and that Warning is still there.

**Comment by rydurham** [comment] 2015-07-25 13:54
Try replacing your current sentry migrations with the new ones in 2.2.3 - does that fix the problem?

**Comment by rydurham** [comment] 2015-07-31 23:32
Did that work for you?

**Comment by ideadx** [comment] 2015-08-08 02:22
Its all good now, sorry for responding late. Thanks. :+1:

**Closed** 2015-08-08 02:22 UTC
